name: Release

on:
  push:
    branches:
      - main
# schedule:
#   - cron: '0 12 2 * *'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Build
        run: |
          python -m scripts.build

      - name: Deploy GitHub page
        uses: crazy-max/ghaction-github-pages@v2
        if: ${{ success() }}
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "d${{ env.date }}"
          message: "Release ${{ steps.date.outputs.date }}"

      - name: Crate new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "d${{ env.date }}"
          title: "Release ${{ env.date }}"
          files: |
            dist/json/*.json
